version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: assessment-engine-postgres
    environment:
      POSTGRES_DB: assessment_engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duck
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: assessment-engine-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "900", "1"]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assessment-engine-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: duck
      DB_NAME: assessment_engine
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assessment-engine-worker
    command: ["node", "dist/workers/worker.main.js"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: duck
      DB_NAME: assessment_engine
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKER_CONCURRENCY: 1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  pgdata:
